name: hotel_booking
description: Hotel Booking App
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.3.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^10.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.5.0
  retrofit: ^4.0.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/images/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/app_icon.png
  min_sdk_android: 21
